### ISSUE TITLE
problems calling mcs with some keyword args

### ISSUE THREAD

**Issue by es335mathwiz** [colintbowers/ForecastEval.jl#3]
I have really enjoyed using your package.  It plays an instrumental role in developing the paper my coauthor and i are writing  (https://www.federalreserve.gov/econres/feds/files/2019074pap.pdf)

I am trying to move from julia 0.6 to 1.3 in steps.   Right now I am having problems going from 0.6 to 0.7;  I am having trouble using a few of the keyword arguments to mcs.

Here is an illustration of the problem

julia> mcs(mexErrs[:,1:5])
Model confidence test results:
    Quadratic form test models in MCS: [5, 2, 1]
    Maximum t-stat test models in MCS: [5, 2, 1]

julia> mcs(mexErrs[:,1:5],alpha=0.07)
ERROR: MethodError: no method matching MCSBoot(::Array{Float64,2}, ::Pair{Symbol,Float64})
Closest candidates are:
  MCSBoot(::Any; alpha, basecaseindex, kwargs...) at /home/garyyrag/.julia/packages/ForecastEval/Qb3En/src/mcs.jl:44
Stacktrace:
 [1] #mcs#17(::Base.Iterators.Pairs{Symbol,Float64,Tuple{Symbol},NamedTuple{(:alpha,),Tuple{Float64}}}, ::Function, ::Array{Float64,2}) at /home/garyyrag/.julia/packages/ForecastEval/Qb3En/src/mcs.jl:239
 [2] (::getfield(ForecastEval, Symbol("#kw##mcs")))(::NamedTuple{(:alpha,),Tuple{Float64}}, ::typeof(mcs), ::Array{Float64,2}) at ./none:0
 [3] top-level scope at none:0

 and here pushed down to the MCSBoot call

julia> MCSBoot(mexErrs[:,1:10],alpha=0.07)
MCSBoot(0.07, Dependent bootstrap input:
    Number of observations in dataset = 127
    Current block length = 13.181896730791978
    Number of resamples = 1000
    Bootstrap method = Stationary bootstrap
    Block length method = Block length selection of Patton, Politis, and White (2009)
    Level 1 statistic = Statistics.mean
    Level 2 statistic = Statistics.var
    Number of observations per resample = 127
    Block length combine function = Statistics.median
, 1)

julia> MCSBoot(mexErrs[:,1:10],alpha=0.07,blocklength=10)
ERROR: MethodError: no method matching DependentBootstrap.BootInput(::Array{Float64,2}, ::Pair{Symbol,Int64})
Closest candidates are:
  DependentBootstrap.BootInput(::Any; blocklength, numresample, bootmethod, blocklengthmethod, flevel1, flevel2, numobsperresample, fblocklengthcombine) at /home/garyyrag/.julia/packages/DependentBootstrap/RGjTu/src/types.jl:204
  DependentBootstrap.BootInput(::Any, ::Int64, ::Float64, ::Int64, ::Tbm<:DependentBootstrap.BootMethod, ::Tbl<:DependentBootstrap.BlockLengthMethod, ::Tf1<:Function, ::Tf2<:Function, ::Int64, ::Tfc<:Function) where {Tbm<:BootMethod, Tbl<:BlockLengthMethod, Tf1<:Function, Tf2<:Function, Tfc<:Function} at /home/garyyrag/.julia/packages/DependentBootstrap/RGjTu/src/types.jl:197
  DependentBootstrap.BootInput(::Any, ::DependentBootstrap.BootInput; blocklength, numresample, bootmethod, blocklengthmethod, flevel1, flevel2, numobsperresample, fblocklengthcombine) at /home/garyyrag/.julia/packages/DependentBootstrap/RGjTu/src/types.jl:223
Stacktrace:
 [1] #MCSBoot#15(::Float64, ::Int64, ::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:blocklength,),Tuple{Int64}}}, ::Type, ::Array{Float64,2}) at /home/garyyrag/.julia/packages/ForecastEval/Qb3En/src/mcs.jl:44
 [2] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:alpha, :blocklength),Tuple{Float64,Int64}}, ::Type{MCSBoot}, ::Array{Float64,2}) at ./none:0
 [3] top-level scope at none:0

julia>

**Comment by colintbowers** [comment]
Thanks for sending this through. It's a problem with the splatting syntax I've used for the keyword wrappers. It needs to be updated for v1+. Foolishly I wrote unit tests for the main routines, but not for the keyword wrappers, so that is why this hasn't come up until now. In my own work I almost always call the main routines directly, so didn't really notice anything was wrong.

In typical fashion, I actually go on holiday tomorrow for a week! The fix itself should be pretty straightforward, but I'm not that familiar with the new `Pkg` process for adding tags to registered packages. I'll see what I can do, but in the meantime you can still use the full functionality of the package by calling the main routine directly.

Here is an example if you already know what block length you want to use when bootstrapping:
```
using DependentBootstrap, ForecastEval
lossmat = rand(50,8) .* collect(1.0:0.1:1.7)';
alpha = 0.05;
bootinput = DependentBootstrap.BootInput(lossmat, bootmethod=:stationary, blocklength=5);
mcsboot = ForecastEval.MCSBoot(alpha, bootinput, 1) #the 1 here is irrelevant since blocklength is supplied
mcsout = ForecastEval.mcs(lossmat, mcsboot)
```
Don't use the above if you don't supply a `blocklength`, since if you do, it'll estimate the block length from `lossmat`, where-as you want to estimate the block length from the loss differentials. So, if you want to estimate the block length from the data, use:
```
using DependentBootstrap, ForecastEval
lossmat = rand(50,8) .* collect(1.0:0.1:1.7)';
basecaseindex = 1; #Specify a base-case for the purposes of estimating block length from loss differentials (this avoids a huge runtime that would occur if you estimated a block length for every possible loss differential combination
lossdiffbasecase = ForecastEval.loss_diff_base_case(lossmat, basecaseindex);
bootinput = DependentBootstrap.BootInput(lossdiffbasecase, bootmethod=:stationary, blocklength=0);
alpha = 0.05;
mcsboot = ForecastEval.MCSBoot(alpha, bootinput, basecaseindex);
mcsout = ForecastEval.mcs(lossmat, mcsboot)
```
Note, you can use `?MCSBoot` and `?BootInput` at the REPL to get detailed info on the construction of these types if you really want to delve into it, but hopefully these examples are enough for the next week. I'll set myself a reminder to look at this as soon as I get back.

**Comment by es335mathwiz** [comment]
Colin,

I was just trying the fix you suggested.  I think I have run into a namespace problem and thought I’d ask if you know how best to resolve a reference to varm.

I have defined the following in a .jl file

++++++++++

using DependentBootstrap, ForecastEval


function interimMCS(lossMat::Matrix{T} ; alpha::Float64=0.05, 
blocklength::Number=0.0, numresample::Number=1000, 
bootmethod::Symbol=:stationary,
blmethod::Symbol=:dummy, basecaseindex::Int=1)::MCSTest where {T<:Number}
bootinput = DependentBootstrap.BootInput(lossmat,
bootmethod=:stationary, blocklength=blocklength);
mcsboot = ForecastEval.MCSBoot(alpha, bootinput, 1) #the 1 here is irrelevant since blocklength is supplied
mcsout = ForecastEval.mcs(lossmat, mcsboot)
end


++++++++

seems fine for 0.6


julia> include("MCSTables.jl")
newMCSExperGEN (generic function with 4 methods)

julia> include("interim.jl")
interimMCS (generic function with 1 method)

julia> res=interimMCS(mexErrs[:,1:4],blocklength=20)


julia> typeof(res)
ForecastEval.MCSTest

julia> VERSION
v"0.6.4"

deprecation messages in v 0.7


julia> include("MCSTables.jl")
[ Info: Recompiling stale cache file /Users/garyanderson/.julia/compiled/v0.7/ForecastEval/fLsID.ji for ForecastEval [c08c26e9-7d88-5404-9cd5-c0fa6a8b90ba]
newMCSExperGEN (generic function with 4 methods)

julia> include("interim.jl")
interimMCS (generic function with 1 method)

julia> res=interimMCS(mexErrs[:,1:4],blocklength=20)
WARNING: importing deprecated binding Base.varm into ForecastEval.
WARNING: Base.varm is deprecated: it has been moved to the standard library package `Statistics`.
Add `using Statistics` to your imports.
 in module ForecastEval
.
.
.
.
.

in mcs at /Users/garyanderson/.julia/packages/ForecastEval/Qb3En/src/mcs.jl
WARNING: Base.varm is deprecated: it has been moved to the standard library package `Statistics`.
Add `using Statistics` to your imports.
 in module ForecastEval
in mcs at /Users/garyanderson/.julia/packages/ForecastEval/Qb3En/src/mcs.jl
Model confidence test results:
    Quadratic form test models in MCS: [2]
    Maximum t-stat test models in MCS: [2]


julia> VERSION
v"0.7.0"

++++++++++++++++++
but fatal problems for 1.0.5

julia> include("MCSTables.jl")
newMCSExperGEN (generic function with 4 methods)

julia> include("interim.jl")
interimMCS (generic function with 1 method)

julia> interimMCS(mexErrs[:,1:4],blocklength=20)
ERROR: UndefVarError: varm not defined
Stacktrace:
 [1] mcs(::Array{Float64,2}, ::MCSBoot) at /Users/garyanderson/.julia/packages/ForecastEval/Qb3En/src/mcs.jl:173
 [2] #interimMCS#138(::Float64, ::Int64, ::Int64, ::Symbol, ::Symbol, ::Int64, ::Function, ::Array{Float64,2}) at /Users/garyanderson/git/EMSovereignCreditSpreads/code/emscsPaper/essential/interim.jl:17
 [3] (::getfield(Main, Symbol("#kw##interimMCS")))(::NamedTuple{(:blocklength,),Tuple{Int64}}, ::typeof(interimMCS), ::Array{Float64,2}) at ./none:0
 [4] top-level scope at none:0

julia> VERSION
v"1.0.5"

julia> methods(varm)
# 7 methods for generic function "varm":
[1] varm(v::AbstractRange, m::AbstractArray) in Statistics at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Statistics/src/Statistics.jl:302
[2] varm(v::AbstractArray{T,N} where N where T<:Real, w::StatsBase.AbstractWeights, m::Real; corrected) in StatsBase at /Users/garyanderson/.julia/packages/StatsBase/DyWPR/src/moments.jl:21
[3] varm(A::AbstractArray{T,N} where N where T<:Real, w::StatsBase.AbstractWeights, M::AbstractArray{T,N} where N where T<:Real, dim::Int64; corrected) in StatsBase at /Users/garyanderson/.julia/packages/StatsBase/DyWPR/src/moments.jl:87
[4] varm(A::AbstractArray, m::AbstractArray; corrected, dims) in Statistics at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Statistics/src/Statistics.jl:259
[5] varm(v::AbstractRange, m) in Statistics at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Statistics/src/Statistics.jl:303
[6] varm(A::AbstractArray, m; corrected) in Statistics at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Statistics/src/Statistics.jl:264
[7] varm(iterable, m; corrected) in Statistics at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Statistics/src/Statistics.jl:298

**Comment by colintbowers** [comment]
Hi Gary,

Sure, varm was in Base until v1.0 when it was moved to the library
Statistics. So you just need to add a "using Statistics" to the using
statements at the top of your ForecastEval.jl file. This is actually
already in the ForecastEval package on the master branch, but it would
appear it isn't on the v1.0 tag. It is clear I really need to tag a new
version of the package, which I will do as soon as I'm home from holidays.
In the meantime, if you can shift to the master branch that should solve
your problem, or else you could just add the aforementioned using statement
locally to the top of you ForecastEval.jl file.

Cheers,

Colin

**Comment by colintbowers** [comment]
Note that all problems raised in this issue should now be fixed on the master branch, plus I've added more unit tests. I'm still in the process of tagging a new version and will close the issue here once I've done that.

**Comment by colintbowers** [comment]
New version with all fixes has been tagged and registered as ForecastEval v1.0.1. You'll need to be running Julia v1.0+ in order to get it via a package update operation. Please let me know if you run into any other issues with the package, and thanks again for your interest.

**Comment by es335mathwiz** [comment]
Colin,
The update Seems to work fine.  Thanks.

Best,
Gary
